name: lite_rt_for_flutter_libs
description: "A new Flutter FFI plugin project."
version: 2.11.0
homepage: https://github.com/CaptainDario/lite_rt_for_flutter_libs/tree/main/liter_rt_for_flutter_libs
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  lite_rt_for_flutter:
    path: ../../lite_rt_for_flutter

#dev_dependencies:


flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

