name: lite_rt_for_flutter_libs
description: "A new Flutter FFI plugin project."
version: 2.17.0
homepage: https://github.com/CaptainDario/lite_rt_for_flutter_libs/tree/main/liter_rt_for_flutter_libs
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  lite_rt_for_flutter_libs_android:
    path: ../lite_rt_for_flutter_libs_android
  lite_rt_for_flutter_libs_ios:
    path: ../lite_rt_for_flutter_libs_ios
  lite_rt_for_flutter_libs_linux:
    path: ../lite_rt_for_flutter_libs_linux
  lite_rt_for_flutter_libs_macos:
    path: ../lite_rt_for_flutter_libs_macos
  lite_rt_for_flutter_libs_web_tfjs_tflite:
    path: ../lite_rt_for_flutter_libs_web_tfjs_tflite
  lite_rt_for_flutter_libs_windows:
    path: ../lite_rt_for_flutter_libs_windows

#dev_dependencies:


flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:

