# This is a basic workflow to help you get started with Actions

name: Build Windows

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tf_version: 
        description: 'TensorFlow version to use (e.g., 2.18.0)'
        required: true
        default: 'v2.18.0'
        type: string

  # allows that other workflows can run this one
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runner.os }}
    strategy:
      matrix:
        runner: 
          - os: windows-2022
            env:
              ARCH: x86
          #- os: windows-11-arm
          #  env:
          #    ARCH: arm64

    env:
      ARCH: ${{ matrix.runner.env.ARCH }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v4
          with:
            submodules: true

        # setup bazel
        - uses: bazel-contrib/setup-bazel@0.14.0
          with:
            # Avoid downloading Bazel every time.
            bazelisk-cache: true
            # Store build cache per workflow.
            disk-cache: ${{ github.workflow }}
            # Share repository cache between workflows.
            repository-cache: true

            output-base: C:/_bazel

        # setup python 3.11
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            
        # checkout tensorflow version
        - name: Checkout tensorflow
          run: |
            cd tensorflow
            git fetch --tags
            git checkout ${{ github.event.inputs.tf_version }}

        # build tf lite
        #- name: Build TF Lite base
        #  shell: bash
        #  run: ./base/build_tf_lite_windows.sh
        #- name: Build TF Lite gpu delegate
        #  shell: bash  
        #  run: ./gpu/build_tf_lite_gpu_delegate_windows.sh
        - name: Build TF Lite flex delegate
          shell: bash
          run: ./flex/build_tf_lite_flex_delegate_windows.sh

        # TODO run test

        # upload the build libs as an artifact
        #- name: upload base library to artifacts
        #  uses: actions/upload-artifact@v4
        #  with:
        #    name: libtensorflowlite_${{env.ARCH}}_c.dll
        #    path: ./tensorflow/libtensorflowlite_${{env.ARCH}}_c.dll
        #- name: upload gpu library to artifacts
        #  uses: actions/upload-artifact@v4
        #  with:
        #    name: libtensorflowlite_${{env.ARCH}}_gpu_delegate_c.dll
        #    path: ./libtensorflowlite_${{env.ARCH}}_gpu_delegate_c.dll
        - name: upload flex library to artifacts
          uses: actions/upload-artifact@v4
          with:
            name: libtensorflowlite_${{env.ARCH}}_flex_delegate_c.dll
            path: ./tensorflow/libtensorflowlite_${{env.ARCH}}_flex_delegate_c.dll