name: lite_rt_for_flutter_libs_web_tfjs_tflite
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/CaptainDario/lite_rt_for_flutter_libs

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_web: ^0.2.2
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      web:

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - web/assets/tflite/
  